services:
  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-keycloak}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - keycloak-network
    # Resource limits, can comment all out below.
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1G"
        reservations:
          cpus: "0.5"
          memory: "512M"

  keycloak:
    image: petesmarttech/keycloak:latest
    build:
      context: .
      dockerfile: Dockerfile.base
    environment:
      # Database connections management
      KC_DB_POOL_INITIAL_SIZE: 10
      KC_DB_POOL_MIN_SIZE: 10
      KC_DB_POOL_MAX_SIZE: 50
      KC_DB_IDLE_TIMEOUT: 300
      # Database connection settings (runtime)
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD:-keycloak}
      # Enable local cache (single-node keycloak)
      KC_CACHE: local
      # Keycloak URL
      KC_HOSTNAME: https://${KEYCLOAK_DOMAIN:-auth.domain.tld}
      # Admin user
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD:-admin}
    ports:
      - "8443:443"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - keycloak-network
    # Resource limits, can comment all out below.
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2G"
        reservations:
          cpus: "1"
          memory: "1G"
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  keycloak-network:
    driver: bridge

volumes:
  postgres_data:
    name: keycloak-postgres-data